return {
{fileName = 'AGENCYB.TTF'; family = 'Agency FB'; subFamilyName = 'Bold'; fullName = 'Agency FB Bold'; postscriptName = 'AgencyFB-Bold'; style = 'NORMAL'; stretch = 3; weight = 700; };
{fileName = 'AGENCYR.TTF'; family = 'Agency FB'; subFamilyName = 'Regular'; fullName = 'Agency FB'; postscriptName = 'AgencyFB-Reg'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'ALGER.TTF'; family = 'Algerian'; subFamilyName = 'Regular'; fullName = 'Algerian'; postscriptName = 'Algerian'; style = 'NORMAL'; stretch = 2; weight = 400; };
{fileName = 'ANTQUAB.TTF'; family = 'Book Antiqua'; subFamilyName = 'Bold'; fullName = 'Book Antiqua Bold'; postscriptName = 'BookAntiqua-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'ANTQUABI.TTF'; family = 'Book Antiqua'; subFamilyName = 'Bold Italic'; fullName = 'Book Antiqua Bold Italic'; postscriptName = 'BookAntiqua-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'ANTQUAI.TTF'; family = 'Book Antiqua'; subFamilyName = 'Italic'; fullName = 'Book Antiqua Italic'; postscriptName = 'BookAntiqua-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'arial.ttf'; family = 'Arial'; subFamilyName = 'Regular'; fullName = 'Arial'; postscriptName = 'ArialMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'arialbd.ttf'; family = 'Arial'; subFamilyName = 'Bold'; fullName = 'Arial Bold'; postscriptName = 'Arial-BoldMT'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'arialbi.ttf'; family = 'Arial'; subFamilyName = 'Bold Italic'; fullName = 'Arial Bold Italic'; postscriptName = 'Arial-BoldItalicMT'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'ariali.ttf'; family = 'Arial'; subFamilyName = 'Italic'; fullName = 'Arial Italic'; postscriptName = 'Arial-ItalicMT'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'ARIALN.TTF'; family = 'Arial'; subFamilyName = 'Narrow'; fullName = 'Arial Narrow'; postscriptName = 'ArialNarrow'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'ARIALNB.TTF'; family = 'Arial'; subFamilyName = 'Narrow Bold'; fullName = 'Arial Narrow Bold'; postscriptName = 'ArialNarrow-Bold'; style = 'NORMAL'; stretch = 3; weight = 700; };
{fileName = 'ARIALNBI.TTF'; family = 'Arial'; subFamilyName = 'Narrow Bold Italic'; fullName = 'Arial Narrow Bold Italic'; postscriptName = 'ArialNarrow-BoldItalic'; style = 'ITALIC'; stretch = 3; weight = 700; };
{fileName = 'ARIALNI.TTF'; family = 'Arial'; subFamilyName = 'Narrow Italic'; fullName = 'Arial Narrow Italic'; postscriptName = 'ArialNarrow-Italic'; style = 'ITALIC'; stretch = 3; weight = 400; };
{fileName = 'ariblk.ttf'; family = 'Arial'; subFamilyName = 'Black'; fullName = 'Arial Black'; postscriptName = 'Arial-Black'; style = 'NORMAL'; stretch = 5; weight = 900; };
{fileName = 'ARLRDBD.TTF'; family = 'Arial Rounded MT Bold'; subFamilyName = 'Regular'; fullName = 'Arial Rounded MT Bold'; postscriptName = 'ArialRoundedMTBold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'bahnschrift.ttf'; family = 'Bahnschrift'; subFamilyName = 'Regular'; fullName = 'Bahnschrift'; postscriptName = 'Bahnschrift'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BASKVILL.TTF'; family = 'Baskerville Old Face'; subFamilyName = 'Regular'; fullName = 'Baskerville Old Face'; postscriptName = 'BaskOldFace'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BAUHS93.TTF'; family = 'Bauhaus 93'; subFamilyName = 'Regular'; fullName = 'Bauhaus 93'; postscriptName = 'Bauhaus93'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BELL.TTF'; family = 'Bell MT'; subFamilyName = 'Regular'; fullName = 'Bell MT'; postscriptName = 'BellMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BELLB.TTF'; family = 'Bell MT'; subFamilyName = 'Bold'; fullName = 'Bell MT Bold'; postscriptName = 'BellMTBold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'BELLI.TTF'; family = 'Bell MT'; subFamilyName = 'Italic'; fullName = 'Bell MT Italic'; postscriptName = 'BellMTItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'BERNHC.TTF'; family = 'Bernard MT Condensed'; subFamilyName = 'Regular'; fullName = 'Bernard MT Condensed'; postscriptName = 'BernardMT-Condensed'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'BKANT.TTF'; family = 'Book Antiqua'; subFamilyName = 'Regular'; fullName = 'Book Antiqua'; postscriptName = 'BookAntiqua'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BOD_B.TTF'; family = 'Bodoni MT'; subFamilyName = 'Bold'; fullName = 'Bodoni MT Bold'; postscriptName = 'BodoniMT-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'BOD_BI.TTF'; family = 'Bodoni MT'; subFamilyName = 'Bold Italic'; fullName = 'Bodoni MT Bold Italic'; postscriptName = 'BodoniMT-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'BOD_BLAI.TTF'; family = 'Bodoni MT'; subFamilyName = 'Black Italic'; fullName = 'Bodoni MT Black Italic'; postscriptName = 'BodoniMTBlack-Italic'; style = 'ITALIC'; stretch = 5; weight = 900; };
{fileName = 'BOD_BLAR.TTF'; family = 'Bodoni MT'; subFamilyName = 'Black'; fullName = 'Bodoni MT Black'; postscriptName = 'BodoniMTBlack'; style = 'NORMAL'; stretch = 5; weight = 900; };
{fileName = 'BOD_CB.TTF'; family = 'Bodoni MT'; subFamilyName = 'Condensed Bold'; fullName = 'Bodoni MT Condensed Bold'; postscriptName = 'BodoniMTCondensed-Bold'; style = 'NORMAL'; stretch = 3; weight = 700; };
{fileName = 'BOD_CBI.TTF'; family = 'Bodoni MT'; subFamilyName = 'Condensed Bold Italic'; fullName = 'Bodoni MT Condensed Bold Italic'; postscriptName = 'BodoniMTCondensed-BoldItalic'; style = 'ITALIC'; stretch = 3; weight = 700; };
{fileName = 'BOD_CI.TTF'; family = 'Bodoni MT'; subFamilyName = 'Condensed Italic'; fullName = 'Bodoni MT Condensed Italic'; postscriptName = 'BodoniMTCondensed-Italic'; style = 'ITALIC'; stretch = 3; weight = 400; };
{fileName = 'BOD_CR.TTF'; family = 'Bodoni MT'; subFamilyName = 'Condensed'; fullName = 'Bodoni MT Condensed'; postscriptName = 'BodoniMTCondensed'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'BOD_I.TTF'; family = 'Bodoni MT'; subFamilyName = 'Italic'; fullName = 'Bodoni MT Italic'; postscriptName = 'BodoniMT-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'BOD_PSTC.TTF'; family = 'Bodoni MT'; subFamilyName = 'Poster Compressed'; fullName = 'Bodoni MT Poster Compressed'; postscriptName = 'BodoniMTPosterCompressed'; style = 'NORMAL'; stretch = 2; weight = 300; };
{fileName = 'BOD_R.TTF'; family = 'Bodoni MT'; subFamilyName = 'Regular'; fullName = 'Bodoni MT'; postscriptName = 'BodoniMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BOOKOS.TTF'; family = 'Bookman Old Style'; subFamilyName = 'Regular'; fullName = 'Bookman Old Style'; postscriptName = 'BookmanOldStyle'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'BOOKOSB.TTF'; family = 'Bookman Old Style'; subFamilyName = 'Bold'; fullName = 'Bookman Old Style Bold'; postscriptName = 'BookmanOldStyle-Bold'; style = 'NORMAL'; stretch = 5; weight = 600; };
{fileName = 'BOOKOSBI.TTF'; family = 'Bookman Old Style'; subFamilyName = 'Bold Italic'; fullName = 'Bookman Old Style Bold Italic'; postscriptName = 'BookmanOldStyle-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 600; };
{fileName = 'BOOKOSI.TTF'; family = 'Bookman Old Style'; subFamilyName = 'Italic'; fullName = 'Bookman Old Style Italic'; postscriptName = 'BookmanOldStyle-Italic'; style = 'ITALIC'; stretch = 5; weight = 300; };
{fileName = 'BRADHITC.TTF'; family = 'Bradley Hand ITC'; subFamilyName = 'Regular'; fullName = 'Bradley Hand ITC'; postscriptName = 'BradleyHandITC'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BRITANIC.TTF'; family = 'Britannic Bold'; subFamilyName = 'Regular'; fullName = 'Britannic Bold'; postscriptName = 'BritannicBold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BRLNSB.TTF'; family = 'Berlin Sans FB'; subFamilyName = 'Bold'; fullName = 'Berlin Sans FB Bold'; postscriptName = 'BerlinSansFB-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'BRLNSDB.TTF'; family = 'Berlin Sans FB Demi'; subFamilyName = 'Bold'; fullName = 'Berlin Sans FB Demi Bold'; postscriptName = 'BerlinSansFBDemi-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'BRLNSR.TTF'; family = 'Berlin Sans FB'; subFamilyName = 'Regular'; fullName = 'Berlin Sans FB'; postscriptName = 'BerlinSansFB-Reg'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BROADW.TTF'; family = 'Broadway'; subFamilyName = 'Regular'; fullName = 'Broadway'; postscriptName = 'Broadway'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'BRUSHSCI.TTF'; family = 'Brush Script MT'; subFamilyName = 'Italic'; fullName = 'Brush Script MT Italic'; postscriptName = 'BrushScriptMT'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'BSSYM7.TTF'; family = 'Bookshelf Symbol 7'; subFamilyName = 'Regular'; fullName = 'Bookshelf Symbol 7'; postscriptName = 'BookshelfSymbolSeven'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'calibri.ttf'; family = 'Calibri'; subFamilyName = 'Regular'; fullName = 'Calibri'; postscriptName = 'Calibri'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'calibrib.ttf'; family = 'Calibri'; subFamilyName = 'Bold'; fullName = 'Calibri Bold'; postscriptName = 'Calibri-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'calibrii.ttf'; family = 'Calibri'; subFamilyName = 'Italic'; fullName = 'Calibri Italic'; postscriptName = 'Calibri-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'calibril.ttf'; family = 'Calibri'; subFamilyName = 'Light'; fullName = 'Calibri Light'; postscriptName = 'Calibri-Light'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'calibrili.ttf'; family = 'Calibri'; subFamilyName = 'Light Italic'; fullName = 'Calibri Light Italic'; postscriptName = 'Calibri-LightItalic'; style = 'ITALIC'; stretch = 5; weight = 300; };
{fileName = 'calibriz.ttf'; family = 'Calibri'; subFamilyName = 'Bold Italic'; fullName = 'Calibri Bold Italic'; postscriptName = 'Calibri-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'CALIFB.TTF'; family = 'Californian FB'; subFamilyName = 'Bold'; fullName = 'Californian FB Bold'; postscriptName = 'CalifornianFB-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'CALIFI.TTF'; family = 'Californian FB'; subFamilyName = 'Italic'; fullName = 'Californian FB Italic'; postscriptName = 'CalifornianFB-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'CALIFR.TTF'; family = 'Californian FB'; subFamilyName = 'Regular'; fullName = 'Californian FB'; postscriptName = 'CalifornianFB-Reg'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CALIST.TTF'; family = 'Calisto MT'; subFamilyName = 'Regular'; fullName = 'Calisto MT'; postscriptName = 'CalistoMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CALISTB.TTF'; family = 'Calisto MT'; subFamilyName = 'Bold'; fullName = 'Calisto MT Bold'; postscriptName = 'CalisMTBol'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'CALISTBI.TTF'; family = 'Calisto MT'; subFamilyName = 'Bold Italic'; fullName = 'Calisto MT Bold Italic'; postscriptName = 'CalistoMT-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'CALISTI.TTF'; family = 'Calisto MT'; subFamilyName = 'Italic'; fullName = 'Calisto MT Italic'; postscriptName = 'CalistoMT-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'cambriab.ttf'; family = 'Cambria'; subFamilyName = 'Bold'; fullName = 'Cambria Bold'; postscriptName = 'Cambria-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'cambriai.ttf'; family = 'Cambria'; subFamilyName = 'Italic'; fullName = 'Cambria Italic'; postscriptName = 'Cambria-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'cambriaz.ttf'; family = 'Cambria'; subFamilyName = 'Bold Italic'; fullName = 'Cambria Bold Italic'; postscriptName = 'Cambria-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'Candara.ttf'; family = 'Candara'; subFamilyName = 'Regular'; fullName = 'Candara'; postscriptName = 'Candara'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'Candarab.ttf'; family = 'Candara'; subFamilyName = 'Bold'; fullName = 'Candara Bold'; postscriptName = 'Candara-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'Candarai.ttf'; family = 'Candara'; subFamilyName = 'Italic'; fullName = 'Candara Italic'; postscriptName = 'Candara-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'Candaral.ttf'; family = 'Candara'; subFamilyName = 'Light'; fullName = 'Candara Light'; postscriptName = 'Candara-Light'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'Candarali.ttf'; family = 'Candara'; subFamilyName = 'Light Italic'; fullName = 'Candara Light Italic'; postscriptName = 'Candara-LightItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'Candaraz.ttf'; family = 'Candara'; subFamilyName = 'Bold Italic'; fullName = 'Candara Bold Italic'; postscriptName = 'Candara-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'CASTELAR.TTF'; family = 'Castellar'; subFamilyName = 'Regular'; fullName = 'Castellar'; postscriptName = 'Castellar'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CENSCBK.TTF'; family = 'Century Schoolbook'; subFamilyName = 'Regular'; fullName = 'Century Schoolbook'; postscriptName = 'CenturySchoolbook'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CENTAUR.TTF'; family = 'Centaur'; subFamilyName = 'Regular'; fullName = 'Centaur'; postscriptName = 'Centaur'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CENTURY.TTF'; family = 'Century'; subFamilyName = 'Regular'; fullName = 'Century'; postscriptName = 'Century'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'CHILLER.TTF'; family = 'Chiller'; subFamilyName = 'Regular'; fullName = 'Chiller'; postscriptName = 'Chiller-Regular'; style = 'NORMAL'; stretch = 6; weight = 400; };
{fileName = 'COLONNA.TTF'; family = 'Colonna MT'; subFamilyName = 'Regular'; fullName = 'Colonna MT'; postscriptName = 'ColonnaMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'comic.ttf'; family = 'Comic Sans MS'; subFamilyName = 'Regular'; fullName = 'Comic Sans MS'; postscriptName = 'ComicSansMS'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'comicbd.ttf'; family = 'Comic Sans MS'; subFamilyName = 'Bold'; fullName = 'Comic Sans MS Bold'; postscriptName = 'ComicSansMS-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'comici.ttf'; family = 'Comic Sans MS'; subFamilyName = 'Italic'; fullName = 'Comic Sans MS Italic'; postscriptName = 'ComicSansMS-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'comicz.ttf'; family = 'Comic Sans MS'; subFamilyName = 'Bold Italic'; fullName = 'Comic Sans MS Bold Italic'; postscriptName = 'ComicSansMS-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'consola.ttf'; family = 'Consolas'; subFamilyName = 'Regular'; fullName = 'Consolas'; postscriptName = 'Consolas'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'consolab.ttf'; family = 'Consolas'; subFamilyName = 'Bold'; fullName = 'Consolas Bold'; postscriptName = 'Consolas-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'consolai.ttf'; family = 'Consolas'; subFamilyName = 'Italic'; fullName = 'Consolas Italic'; postscriptName = 'Consolas-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'consolaz.ttf'; family = 'Consolas'; subFamilyName = 'Bold Italic'; fullName = 'Consolas Bold Italic'; postscriptName = 'Consolas-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'constan.ttf'; family = 'Constantia'; subFamilyName = 'Regular'; fullName = 'Constantia'; postscriptName = 'Constantia'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'constanb.ttf'; family = 'Constantia'; subFamilyName = 'Bold'; fullName = 'Constantia Bold'; postscriptName = 'Constantia-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'constani.ttf'; family = 'Constantia'; subFamilyName = 'Italic'; fullName = 'Constantia Italic'; postscriptName = 'Constantia-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'constanz.ttf'; family = 'Constantia'; subFamilyName = 'Bold Italic'; fullName = 'Constantia Bold Italic'; postscriptName = 'Constantia-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'COOPBL.TTF'; family = 'Cooper Black'; subFamilyName = 'Regular'; fullName = 'Cooper Black'; postscriptName = 'CooperBlack'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'COPRGTB.TTF'; family = 'Copperplate Gothic Bold'; subFamilyName = 'Regular'; fullName = 'Copperplate Gothic Bold'; postscriptName = 'CopperplateGothic-Bold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'COPRGTL.TTF'; family = 'Copperplate Gothic Light'; subFamilyName = 'Regular'; fullName = 'Copperplate Gothic Light'; postscriptName = 'CopperplateGothic-Light'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'corbel.ttf'; family = 'Corbel'; subFamilyName = 'Regular'; fullName = 'Corbel'; postscriptName = 'Corbel'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'corbelb.ttf'; family = 'Corbel'; subFamilyName = 'Bold'; fullName = 'Corbel Bold'; postscriptName = 'Corbel-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'corbeli.ttf'; family = 'Corbel'; subFamilyName = 'Italic'; fullName = 'Corbel Italic'; postscriptName = 'Corbel-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'corbell.ttf'; family = 'Corbel'; subFamilyName = 'Light'; fullName = 'Corbel Light'; postscriptName = 'CorbelLight'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'corbelli.ttf'; family = 'Corbel'; subFamilyName = 'Light Italic'; fullName = 'Corbel Light Italic'; postscriptName = 'CorbelLight-Italic'; style = 'ITALIC'; stretch = 5; weight = 300; };
{fileName = 'corbelz.ttf'; family = 'Corbel'; subFamilyName = 'Bold Italic'; fullName = 'Corbel Bold Italic'; postscriptName = 'Corbel-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'cour.ttf'; family = 'Courier New'; subFamilyName = 'Regular'; fullName = 'Courier New'; postscriptName = 'CourierNewPSMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'courbd.ttf'; family = 'Courier New'; subFamilyName = 'Bold'; fullName = 'Courier New Bold'; postscriptName = 'CourierNewPS-BoldMT'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'courbi.ttf'; family = 'Courier New'; subFamilyName = 'Bold Italic'; fullName = 'Courier New Bold Italic'; postscriptName = 'CourierNewPS-BoldItalicMT'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'couri.ttf'; family = 'Courier New'; subFamilyName = 'Italic'; fullName = 'Courier New Italic'; postscriptName = 'CourierNewPS-ItalicMT'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'CURLZ___.TTF'; family = 'Curlz MT'; subFamilyName = 'Regular'; fullName = 'Curlz MT'; postscriptName = 'CurlzMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'DUBAI-BOLD.TTF'; family = 'Dubai'; subFamilyName = 'Bold'; fullName = 'Dubai Bold'; postscriptName = 'Dubai-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'DUBAI-LIGHT.TTF'; family = 'Dubai'; subFamilyName = 'Light'; fullName = 'Dubai Light'; postscriptName = 'Dubai-Light'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'DUBAI-MEDIUM.TTF'; family = 'Dubai'; subFamilyName = 'Medium'; fullName = 'Dubai Medium'; postscriptName = 'Dubai-Medium'; style = 'NORMAL'; stretch = 5; weight = 500; };
{fileName = 'DUBAI-REGULAR.TTF'; family = 'Dubai'; subFamilyName = 'Regular'; fullName = 'Dubai Regular'; postscriptName = 'Dubai-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ebrima.ttf'; family = 'Ebrima'; subFamilyName = 'Regular'; fullName = 'Ebrima'; postscriptName = 'Ebrima'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ebrimabd.ttf'; family = 'Ebrima'; subFamilyName = 'Bold'; fullName = 'Ebrima Bold'; postscriptName = 'Ebrima-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'ELEPHNT.TTF'; family = 'Elephant'; subFamilyName = 'Regular'; fullName = 'Elephant'; postscriptName = 'Elephant-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ELEPHNTI.TTF'; family = 'Elephant'; subFamilyName = 'Italic'; fullName = 'Elephant Italic'; postscriptName = 'Elephant-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'ENGR.TTF'; family = 'Engravers MT'; subFamilyName = 'Regular'; fullName = 'Engravers MT'; postscriptName = 'EngraversMT'; style = 'NORMAL'; stretch = 7; weight = 500; };
{fileName = 'ERASBD.TTF'; family = 'Eras Bold ITC'; subFamilyName = 'Regular'; fullName = 'Eras Bold ITC'; postscriptName = 'ErasITC-Bold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ERASDEMI.TTF'; family = 'Eras Demi ITC'; subFamilyName = 'Regular'; fullName = 'Eras Demi ITC'; postscriptName = 'ErasITC-Demi'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ERASLGHT.TTF'; family = 'Eras Light ITC'; subFamilyName = 'Regular'; fullName = 'Eras Light ITC'; postscriptName = 'ErasITC-Light'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ERASMD.TTF'; family = 'Eras Medium ITC'; subFamilyName = 'Regular'; fullName = 'Eras Medium ITC'; postscriptName = 'ErasITC-Medium'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FELIXTI.TTF'; family = 'Felix Titling'; subFamilyName = 'Regular'; fullName = 'Felix Titling'; postscriptName = 'FelixTitlingMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FORTE.TTF'; family = 'Forte'; subFamilyName = 'Regular'; fullName = 'Forte'; postscriptName = 'ForteMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRABK.TTF'; family = 'Franklin Gothic Book'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Book'; postscriptName = 'FranklinGothic-Book'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRABKIT.TTF'; family = 'Franklin Gothic Book'; subFamilyName = 'Italic'; fullName = 'Franklin Gothic Book Italic'; postscriptName = 'FranklinGothic-BookItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'FRADM.TTF'; family = 'Franklin Gothic Demi'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Demi'; postscriptName = 'FranklinGothic-Demi'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRADMCN.TTF'; family = 'Franklin Gothic Demi Cond'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Demi Cond'; postscriptName = 'FranklinGothic-DemiCond'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'FRADMIT.TTF'; family = 'Franklin Gothic Demi'; subFamilyName = 'Italic'; fullName = 'Franklin Gothic Demi Italic'; postscriptName = 'FranklinGothic-DemiItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'FRAHV.TTF'; family = 'Franklin Gothic Heavy'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Heavy'; postscriptName = 'FranklinGothic-Heavy'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRAHVIT.TTF'; family = 'Franklin Gothic Heavy'; subFamilyName = 'Italic'; fullName = 'Franklin Gothic Heavy Italic'; postscriptName = 'FranklinGothic-HeavyItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'framd.ttf'; family = 'Franklin Gothic Medium'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Medium'; postscriptName = 'FranklinGothic-Medium'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRAMDCN.TTF'; family = 'Franklin Gothic Medium Cond'; subFamilyName = 'Regular'; fullName = 'Franklin Gothic Medium Cond'; postscriptName = 'FranklinGothic-MediumCond'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'framdit.ttf'; family = 'Franklin Gothic Medium'; subFamilyName = 'Italic'; fullName = 'Franklin Gothic Medium Italic'; postscriptName = 'FranklinGothic-MediumItalic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'FREESCPT.TTF'; family = 'Freestyle Script'; subFamilyName = 'Regular'; fullName = 'Freestyle Script'; postscriptName = 'FreestyleScript-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FRSCRIPT.TTF'; family = 'French Script MT'; subFamilyName = 'Regular'; fullName = 'French Script MT'; postscriptName = 'FrenchScriptMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'FTLTLT.TTF'; family = 'Footlight MT Light'; subFamilyName = 'Regular'; fullName = 'Footlight MT Light'; postscriptName = 'FootlightMTLight'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'Gabriola.ttf'; family = 'Gabriola'; subFamilyName = 'Regular'; fullName = 'Gabriola'; postscriptName = 'Gabriola'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'gadugi.ttf'; family = 'Gadugi'; subFamilyName = 'Regular'; fullName = 'Gadugi'; postscriptName = 'Gadugi'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'gadugib.ttf'; family = 'Gadugi'; subFamilyName = 'Bold'; fullName = 'Gadugi Bold'; postscriptName = 'Gadugi-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'GARA.TTF'; family = 'Garamond'; subFamilyName = 'Regular'; fullName = 'Garamond'; postscriptName = 'Garamond'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'GARABD.TTF'; family = 'Garamond'; subFamilyName = 'Bold'; fullName = 'Garamond Bold'; postscriptName = 'Garamond-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'GARAIT.TTF'; family = 'Garamond'; subFamilyName = 'Italic'; fullName = 'Garamond Italic'; postscriptName = 'Garamond-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'georgia.ttf'; family = 'Georgia'; subFamilyName = 'Regular'; fullName = 'Georgia'; postscriptName = 'Georgia'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'georgiab.ttf'; family = 'Georgia'; subFamilyName = 'Bold'; fullName = 'Georgia Bold'; postscriptName = 'Georgia-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'georgiai.ttf'; family = 'Georgia'; subFamilyName = 'Italic'; fullName = 'Georgia Italic'; postscriptName = 'Georgia-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'georgiaz.ttf'; family = 'Georgia'; subFamilyName = 'Bold Italic'; fullName = 'Georgia Bold Italic'; postscriptName = 'Georgia-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'GIGI.TTF'; family = 'Gigi'; subFamilyName = 'Regular'; fullName = 'Gigi'; postscriptName = 'Gigi-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'GILBI___.TTF'; family = 'Gill Sans MT'; subFamilyName = 'Bold Italic'; fullName = 'Gill Sans MT Bold Italic'; postscriptName = 'GillSansMT-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'GILB____.TTF'; family = 'Gill Sans MT'; subFamilyName = 'Bold'; fullName = 'Gill Sans MT Bold'; postscriptName = 'GillSansMT-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'GILC____.TTF'; family = 'Gill Sans MT Condensed'; subFamilyName = 'Regular'; fullName = 'Gill Sans MT Condensed'; postscriptName = 'GillSansMT-Condensed'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'GILI____.TTF'; family = 'Gill Sans MT'; subFamilyName = 'Italic'; fullName = 'Gill Sans MT Italic'; postscriptName = 'GillSansMT-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'GILLUBCD.TTF'; family = 'Gill Sans Ultra Bold Condensed'; subFamilyName = 'Regular'; fullName = 'Gill Sans Ultra Bold Condensed'; postscriptName = 'GillSans-UltraBoldCondensed'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'GILSANUB.TTF'; family = 'Gill Sans Ultra Bold'; subFamilyName = 'Regular'; fullName = 'Gill Sans Ultra Bold'; postscriptName = 'GillSans-UltraBold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'GIL_____.TTF'; family = 'Gill Sans MT'; subFamilyName = 'Regular'; fullName = 'Gill Sans MT'; postscriptName = 'GillSansMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'GLECB.TTF'; family = 'Gloucester MT Extra Condensed'; subFamilyName = 'Regular'; fullName = 'Gloucester MT Extra Condensed'; postscriptName = 'GloucesterMT-ExtraCondensed'; style = 'NORMAL'; stretch = 2; weight = 400; };
{fileName = 'GLSNECB.TTF'; family = 'Gill Sans MT Ext Condensed Bold'; subFamilyName = 'Regular'; fullName = 'Gill Sans MT Ext Condensed Bold'; postscriptName = 'GillSansMT-ExtraCondensedBold'; style = 'NORMAL'; stretch = 2; weight = 400; };
{fileName = 'GOTHIC.TTF'; family = 'Century Gothic'; subFamilyName = 'Regular'; fullName = 'Century Gothic'; postscriptName = 'CenturyGothic'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'GOTHICB.TTF'; family = 'Century Gothic'; subFamilyName = 'Bold'; fullName = 'Century Gothic Bold'; postscriptName = 'CenturyGothic-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'GOTHICBI.TTF'; family = 'Century Gothic'; subFamilyName = 'Bold Italic'; fullName = 'Century Gothic Bold Italic'; postscriptName = 'CenturyGothic-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'GOTHICI.TTF'; family = 'Century Gothic'; subFamilyName = 'Italic'; fullName = 'Century Gothic Italic'; postscriptName = 'CenturyGothic-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'GOUDOS.TTF'; family = 'Goudy Old Style'; subFamilyName = 'Regular'; fullName = 'Goudy Old Style'; postscriptName = 'GoudyOldStyleT-Regular'; style = 'NORMAL'; stretch = 6; weight = 400; };
{fileName = 'GOUDOSB.TTF'; family = 'Goudy Old Style'; subFamilyName = 'Bold'; fullName = 'Goudy Old Style Bold'; postscriptName = 'GoudyOldStyleT-Bold'; style = 'NORMAL'; stretch = 6; weight = 700; };
{fileName = 'GOUDOSI.TTF'; family = 'Goudy Old Style'; subFamilyName = 'Italic'; fullName = 'Goudy Old Style Italic'; postscriptName = 'GoudyOldStyleT-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'GOUDYSTO.TTF'; family = 'Goudy Stout'; subFamilyName = 'Regular'; fullName = 'Goudy Stout'; postscriptName = 'GoudyStout'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'HARLOWSI.TTF'; family = 'Harlow Solid Italic'; subFamilyName = ''; fullName = 'Harlow Solid Italic'; postscriptName = 'HarlowSolid'; style = 'ITALIC'; stretch = 6; weight = 400; };
{fileName = 'HARNGTON.TTF'; family = 'Harrington'; subFamilyName = 'Regular'; fullName = 'Harrington'; postscriptName = 'Harrington'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'HATTEN.TTF'; family = 'Haettenschweiler'; subFamilyName = 'Regular'; fullName = 'Haettenschweiler'; postscriptName = 'Haettenschweiler'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'himalaya.ttf'; family = 'Microsoft Himalaya'; subFamilyName = 'Regular'; fullName = 'Microsoft Himalaya'; postscriptName = 'Microsoft Himalaya'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'holomdl2.ttf'; family = 'HoloLens MDL2 Assets'; subFamilyName = 'Regular'; fullName = 'HoloLens MDL2 Assets'; postscriptName = 'HoloLensMDL2Assets'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'HTOWERT.TTF'; family = 'High Tower Text'; subFamilyName = 'Regular'; fullName = 'High Tower Text'; postscriptName = 'HighTowerText-Reg'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'HTOWERTI.TTF'; family = 'High Tower Text'; subFamilyName = 'Italic'; fullName = 'High Tower Text Italic'; postscriptName = 'HighTowerText-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'impact.ttf'; family = 'Impact'; subFamilyName = 'Regular'; fullName = 'Impact'; postscriptName = 'Impact'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'IMPRISHA.TTF'; family = 'Imprint MT Shadow'; subFamilyName = 'Regular'; fullName = 'Imprint MT Shadow'; postscriptName = 'ImprintMT-Shadow'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'INFROMAN.TTF'; family = 'Informal Roman'; subFamilyName = 'Regular'; fullName = 'Informal Roman'; postscriptName = 'InformalRoman-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'Inkfree.ttf'; family = 'Ink Free'; subFamilyName = 'Regular'; fullName = 'Ink Free'; postscriptName = 'InkFree'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ITCBLKAD.TTF'; family = 'Blackadder ITC'; subFamilyName = 'Regular'; fullName = 'Blackadder ITC'; postscriptName = 'BlackadderITC-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ITCEDSCR.TTF'; family = 'Edwardian Script ITC'; subFamilyName = 'Regular'; fullName = 'Edwardian Script ITC'; postscriptName = 'EdwardianScriptITC'; style = 'NORMAL'; stretch = 6; weight = 400; };
{fileName = 'ITCKRIST.TTF'; family = 'Kristen ITC'; subFamilyName = 'Regular'; fullName = 'Kristen ITC'; postscriptName = 'KristenITC-Regular'; style = 'NORMAL'; stretch = 6; weight = 400; };
{fileName = 'javatext.ttf'; family = 'Javanese Text'; subFamilyName = 'Regular'; fullName = 'Javanese Text'; postscriptName = 'JavaneseText'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'JOKERMAN.TTF'; family = 'Jokerman'; subFamilyName = 'Regular'; fullName = 'Jokerman'; postscriptName = 'Jokerman-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'JUICE___.TTF'; family = 'Juice ITC'; subFamilyName = 'Regular'; fullName = 'Juice ITC'; postscriptName = 'JuiceITC-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'KUNSTLER.TTF'; family = 'Kunstler Script'; subFamilyName = 'Regular'; fullName = 'Kunstler Script'; postscriptName = 'KunstlerScript'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LATINWD.TTF'; family = 'Wide Latin'; subFamilyName = 'Regular'; fullName = 'Wide Latin'; postscriptName = 'LatinWide'; style = 'NORMAL'; stretch = 9; weight = 400; };
{fileName = 'LBRITE.TTF'; family = 'Lucida Bright'; subFamilyName = 'Regular'; fullName = 'Lucida Bright'; postscriptName = 'LucidaBright'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LBRITED.TTF'; family = 'Lucida Bright'; subFamilyName = 'Demibold'; fullName = 'Lucida Bright Demibold'; postscriptName = 'LucidaBright-Demi'; style = 'NORMAL'; stretch = 5; weight = 600; };
{fileName = 'LBRITEDI.TTF'; family = 'Lucida Bright'; subFamilyName = 'Demibold Italic'; fullName = 'Lucida Bright Demibold Italic'; postscriptName = 'LucidaBright-DemiItalic'; style = 'ITALIC'; stretch = 5; weight = 600; };
{fileName = 'LBRITEI.TTF'; family = 'Lucida Bright'; subFamilyName = 'Italic'; fullName = 'Lucida Bright Italic'; postscriptName = 'LucidaBright-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'LCALLIG.TTF'; family = 'Lucida Calligraphy'; subFamilyName = 'Italic'; fullName = 'Lucida Calligraphy Italic'; postscriptName = 'LucidaCalligraphy-Italic'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LeelaUIb.ttf'; family = 'Leelawadee UI'; subFamilyName = 'Bold'; fullName = 'Leelawadee UI Bold'; postscriptName = 'LeelawadeeUI-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'LeelawUI.ttf'; family = 'Leelawadee UI'; subFamilyName = 'Regular'; fullName = 'Leelawadee UI'; postscriptName = 'LeelawadeeUI'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LeelUIsl.ttf'; family = 'Leelawadee UI'; subFamilyName = 'Semilight'; fullName = 'Leelawadee UI Semilight'; postscriptName = 'LeelawadeeUI-Semilight'; style = 'NORMAL'; stretch = 5; weight = 350; };
{fileName = 'LFAX.TTF'; family = 'Lucida Fax'; subFamilyName = 'Regular'; fullName = 'Lucida Fax Regular'; postscriptName = 'LucidaFax'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LFAXD.TTF'; family = 'Lucida Fax'; subFamilyName = 'Demibold'; fullName = 'Lucida Fax Demibold'; postscriptName = 'LucidaFax-Demi'; style = 'NORMAL'; stretch = 5; weight = 600; };
{fileName = 'LFAXDI.TTF'; family = 'Lucida Fax'; subFamilyName = 'Demibold Italic'; fullName = 'Lucida Fax Demibold Italic'; postscriptName = 'LucidaFax-DemiItalic'; style = 'ITALIC'; stretch = 5; weight = 600; };
{fileName = 'LFAXI.TTF'; family = 'Lucida Fax'; subFamilyName = 'Italic'; fullName = 'Lucida Fax Italic'; postscriptName = 'LucidaFax-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'LHANDW.TTF'; family = 'Lucida Handwriting'; subFamilyName = 'Italic'; fullName = 'Lucida Handwriting Italic'; postscriptName = 'LucidaHandwriting-Italic'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LSANS.TTF'; family = 'Lucida Sans'; subFamilyName = 'Regular'; fullName = 'Lucida Sans Regular'; postscriptName = 'LucidaSans'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'LSANSD.TTF'; family = 'Lucida Sans'; subFamilyName = 'Demibold Roman'; fullName = 'Lucida Sans Demibold Roman'; postscriptName = 'LucidaSans-Demi'; style = 'NORMAL'; stretch = 5; weight = 600; };
{fileName = 'LSANSDI.TTF'; family = 'Lucida Sans'; subFamilyName = 'Demibold Italic'; fullName = 'Lucida Sans Demibold Italic'; postscriptName = 'LucidaSans-DemiItalic'; style = 'ITALIC'; stretch = 5; weight = 600; };
{fileName = 'LSANSI.TTF'; family = 'Lucida Sans'; subFamilyName = 'Italic'; fullName = 'Lucida Sans Italic'; postscriptName = 'LucidaSans-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'LTYPE.TTF'; family = 'Lucida Sans Typewriter'; subFamilyName = 'Regular'; fullName = 'Lucida Sans Typewriter Regular'; postscriptName = 'LucidaSans-Typewriter'; style = 'NORMAL'; stretch = 4; weight = 400; };
{fileName = 'LTYPEB.TTF'; family = 'Lucida Sans Typewriter'; subFamilyName = 'Bold'; fullName = 'Lucida Sans Typewriter Bold'; postscriptName = 'LucidaSans-TypewriterBold'; style = 'NORMAL'; stretch = 4; weight = 600; };
{fileName = 'LTYPEBO.TTF'; family = 'Lucida Sans Typewriter'; subFamilyName = 'Bold Oblique'; fullName = 'Lucida Sans Typewriter Bold Oblique'; postscriptName = 'LucidaSans-TypewriterBoldOblique'; style = 'ITALIC'; stretch = 4; weight = 600; };
{fileName = 'LTYPEO.TTF'; family = 'Lucida Sans Typewriter'; subFamilyName = 'Oblique'; fullName = 'Lucida Sans Typewriter Oblique'; postscriptName = 'LucidaSans-TypewriterOblique'; style = 'ITALIC'; stretch = 4; weight = 400; };
{fileName = 'lucon.ttf'; family = 'Lucida Console'; subFamilyName = 'Regular'; fullName = 'Lucida Console'; postscriptName = 'LucidaConsole'; style = 'NORMAL'; stretch = 4; weight = 400; };
{fileName = 'l_10646.ttf'; family = 'Lucida Sans Unicode'; subFamilyName = 'Regular'; fullName = 'Lucida Sans Unicode'; postscriptName = 'LucidaSansUnicode'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'MAGNETOB.TTF'; family = 'Magneto'; subFamilyName = 'Bold'; fullName = 'Magneto Bold'; postscriptName = 'Magneto-Bold'; style = 'NORMAL'; stretch = 6; weight = 700; };
{fileName = 'MAIAN.TTF'; family = 'Maiandra GD'; subFamilyName = 'Regular'; fullName = 'Maiandra GD'; postscriptName = 'MaiandraGD-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'malgun.ttf'; family = 'Malgun Gothic'; subFamilyName = 'Regular'; fullName = 'Malgun Gothic'; postscriptName = 'MalgunGothic'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'malgunbd.ttf'; family = 'Malgun Gothic'; subFamilyName = 'Bold'; fullName = 'Malgun Gothic Bold'; postscriptName = 'MalgunGothicBold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'malgunsl.ttf'; family = 'Malgun Gothic'; subFamilyName = 'Semilight'; fullName = 'Malgun Gothic Semilight'; postscriptName = 'MalgunGothic-Semilight'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'marlett.ttf'; family = 'Marlett'; subFamilyName = 'Regular'; fullName = 'Marlett'; postscriptName = 'Marlett'; style = 'NORMAL'; stretch = 5; weight = 500; };
{fileName = 'MATURASC.TTF'; family = 'Matura MT Script Capitals'; subFamilyName = 'Regular'; fullName = 'Matura MT Script Capitals'; postscriptName = 'MaturaMTScriptCapitals'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'micross.ttf'; family = 'Microsoft Sans Serif'; subFamilyName = 'Regular'; fullName = 'Microsoft Sans Serif'; postscriptName = 'MicrosoftSansSerif'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'MISTRAL.TTF'; family = 'Mistral'; subFamilyName = 'Regular'; fullName = 'Mistral'; postscriptName = 'Mistral'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'mmrtext.ttf'; family = 'Myanmar Text'; subFamilyName = 'Regular'; fullName = 'Myanmar Text'; postscriptName = 'MyanmarText'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'mmrtextb.ttf'; family = 'Myanmar Text'; subFamilyName = 'Bold'; fullName = 'Myanmar Text Bold'; postscriptName = 'MyanmarText-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'MOD20.TTF'; family = 'Modern No. 20'; subFamilyName = 'Regular'; fullName = 'Modern No. 20'; postscriptName = 'Modern-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'monbaiti.ttf'; family = 'Mongolian Baiti'; subFamilyName = 'Regular'; fullName = 'Mongolian Baiti'; postscriptName = 'MongolianBaiti'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'msyi.ttf'; family = 'Microsoft Yi Baiti'; subFamilyName = 'Regular'; fullName = 'Microsoft Yi Baiti'; postscriptName = 'Microsoft-Yi-Baiti'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'MTCORSVA.TTF'; family = 'Monotype Corsiva'; subFamilyName = 'Regular'; fullName = 'Monotype Corsiva'; postscriptName = 'MonotypeCorsiva'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'MTEXTRA.TTF'; family = 'MT Extra'; subFamilyName = 'Regular'; fullName = 'MT Extra'; postscriptName = 'MT-Extra'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'mvboli.ttf'; family = 'MV Boli'; subFamilyName = 'Regular'; fullName = 'MV Boli'; postscriptName = 'MVBoli'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'NIAGENG.TTF'; family = 'Niagara Engraved'; subFamilyName = 'Regular'; fullName = 'Niagara Engraved'; postscriptName = 'NiagaraEngraved-Reg'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'NIAGSOL.TTF'; family = 'Niagara Solid'; subFamilyName = 'Regular'; fullName = 'Niagara Solid'; postscriptName = 'NiagaraSolid-Reg'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'Nirmala.ttf'; family = 'Nirmala UI'; subFamilyName = 'Regular'; fullName = 'Nirmala UI'; postscriptName = 'NirmalaUI'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'NirmalaB.ttf'; family = 'Nirmala UI'; subFamilyName = 'Bold'; fullName = 'Nirmala UI Bold'; postscriptName = 'NirmalaUI-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'NirmalaS.ttf'; family = 'Nirmala UI'; subFamilyName = 'Semilight'; fullName = 'Nirmala UI Semilight'; postscriptName = 'NirmalaUI-Semilight'; style = 'NORMAL'; stretch = 5; weight = 350; };
{fileName = 'ntailu.ttf'; family = 'Microsoft New Tai Lue'; subFamilyName = 'Regular'; fullName = 'Microsoft New Tai Lue'; postscriptName = 'MicrosoftNewTaiLue'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ntailub.ttf'; family = 'Microsoft New Tai Lue'; subFamilyName = 'Bold'; fullName = 'Microsoft New Tai Lue Bold'; postscriptName = 'MicrosoftNewTaiLue-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'OCRAEXT.TTF'; family = 'OCR A Extended'; subFamilyName = 'Regular'; fullName = 'OCR A Extended'; postscriptName = 'OCRAExtended'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'OLDENGL.TTF'; family = 'Old English Text MT'; subFamilyName = 'Regular'; fullName = 'Old English Text MT'; postscriptName = 'OldEnglishTextMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ONYX.TTF'; family = 'Onyx'; subFamilyName = 'Regular'; fullName = 'Onyx'; postscriptName = 'Onyx'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'OUTLOOK.TTF'; family = 'MS Outlook'; subFamilyName = 'Regular'; fullName = 'MS Outlook'; postscriptName = 'MSOutlook'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'pala.ttf'; family = 'Palatino Linotype'; subFamilyName = 'Regular'; fullName = 'Palatino Linotype'; postscriptName = 'PalatinoLinotype-Roman'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'palab.ttf'; family = 'Palatino Linotype'; subFamilyName = 'Bold'; fullName = 'Palatino Linotype Bold'; postscriptName = 'PalatinoLinotype-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'palabi.ttf'; family = 'Palatino Linotype'; subFamilyName = 'Bold Italic'; fullName = 'Palatino Linotype Bold Italic'; postscriptName = 'PalatinoLinotype-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'palai.ttf'; family = 'Palatino Linotype'; subFamilyName = 'Italic'; fullName = 'Palatino Linotype Italic'; postscriptName = 'PalatinoLinotype-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'PALSCRI.TTF'; family = 'Palace Script MT'; subFamilyName = 'Regular'; fullName = 'Palace Script MT'; postscriptName = 'PalaceScriptMT'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'PAPYRUS.TTF'; family = 'Papyrus'; subFamilyName = 'Regular'; fullName = 'Papyrus'; postscriptName = 'Papyrus-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'PARCHM.TTF'; family = 'Parchment'; subFamilyName = 'Regular'; fullName = 'Parchment'; postscriptName = 'Parchment-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'PERBI___.TTF'; family = 'Perpetua'; subFamilyName = 'Bold Italic'; fullName = 'Perpetua Bold Italic'; postscriptName = 'Perpetua-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'PERB____.TTF'; family = 'Perpetua'; subFamilyName = 'Bold'; fullName = 'Perpetua Bold'; postscriptName = 'Perpetua-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'PERI____.TTF'; family = 'Perpetua'; subFamilyName = 'Italic'; fullName = 'Perpetua Italic'; postscriptName = 'Perpetua-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'PERTIBD.TTF'; family = 'Perpetua Titling MT'; subFamilyName = 'Bold'; fullName = 'Perpetua Titling MT Bold'; postscriptName = 'PerpetuaTitlingMT-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'PERTILI.TTF'; family = 'Perpetua Titling MT'; subFamilyName = 'Light'; fullName = 'Perpetua Titling MT Light'; postscriptName = 'PerpetuaTitlingMT-Light'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'PER_____.TTF'; family = 'Perpetua'; subFamilyName = 'Regular'; fullName = 'Perpetua'; postscriptName = 'Perpetua'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'phagspa.ttf'; family = 'Microsoft PhagsPa'; subFamilyName = 'Regular'; fullName = 'Microsoft PhagsPa'; postscriptName = 'MicrosoftPhagsPa'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'phagspab.ttf'; family = 'Microsoft PhagsPa'; subFamilyName = 'Bold'; fullName = 'Microsoft PhagsPa Bold'; postscriptName = 'MicrosoftPhagsPa-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'PLAYBILL.TTF'; family = 'Playbill'; subFamilyName = 'Regular'; fullName = 'Playbill'; postscriptName = 'Playbill'; style = 'NORMAL'; stretch = 1; weight = 400; };
{fileName = 'POORICH.TTF'; family = 'Poor Richard'; subFamilyName = 'Regular'; fullName = 'Poor Richard'; postscriptName = 'PoorRichard-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'PRISTINA.TTF'; family = 'Pristina'; subFamilyName = 'Regular'; fullName = 'Pristina'; postscriptName = 'Pristina-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'RAGE.TTF'; family = 'Rage Italic'; subFamilyName = 'Regular'; fullName = 'Rage Italic'; postscriptName = 'RageItalic'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'RAVIE.TTF'; family = 'Ravie'; subFamilyName = 'Regular'; fullName = 'Ravie'; postscriptName = 'Ravie'; style = 'NORMAL'; stretch = 6; weight = 400; };
{fileName = 'REFSAN.TTF'; family = 'MS Reference Sans Serif'; subFamilyName = 'Regular'; fullName = 'MS Reference Sans Serif'; postscriptName = 'MSReferenceSansSerif'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'REFSPCL.TTF'; family = 'MS Reference Specialty'; subFamilyName = 'Regular'; fullName = 'MS Reference Specialty'; postscriptName = 'MSReferenceSpecialty'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ROCCB___.TTF'; family = 'Rockwell Condensed'; subFamilyName = 'Bold'; fullName = 'Rockwell Condensed Bold'; postscriptName = 'Rockwell-CondensedBold'; style = 'NORMAL'; stretch = 3; weight = 700; };
{fileName = 'ROCC____.TTF'; family = 'Rockwell Condensed'; subFamilyName = 'Regular'; fullName = 'Rockwell Condensed'; postscriptName = 'Rockwell-Condensed'; style = 'NORMAL'; stretch = 3; weight = 400; };
{fileName = 'ROCK.TTF'; family = 'Rockwell'; subFamilyName = 'Regular'; fullName = 'Rockwell'; postscriptName = 'Rockwell'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'ROCKB.TTF'; family = 'Rockwell'; subFamilyName = 'Bold'; fullName = 'Rockwell Bold'; postscriptName = 'Rockwell-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'ROCKBI.TTF'; family = 'Rockwell'; subFamilyName = 'Bold Italic'; fullName = 'Rockwell Bold Italic'; postscriptName = 'Rockwell-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'ROCKEB.TTF'; family = 'Rockwell Extra Bold'; subFamilyName = 'Regular'; fullName = 'Rockwell Extra Bold'; postscriptName = 'Rockwell-ExtraBold'; style = 'NORMAL'; stretch = 5; weight = 800; };
{fileName = 'ROCKI.TTF'; family = 'Rockwell'; subFamilyName = 'Italic'; fullName = 'Rockwell Italic'; postscriptName = 'Rockwell-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'SCHLBKB.TTF'; family = 'Century Schoolbook'; subFamilyName = 'Bold'; fullName = 'Century Schoolbook Bold'; postscriptName = 'CenturySchoolbook-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'SCHLBKBI.TTF'; family = 'Century Schoolbook'; subFamilyName = 'Bold Italic'; fullName = 'Century Schoolbook Bold Italic'; postscriptName = 'CenturySchoolbook-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'SCHLBKI.TTF'; family = 'Century Schoolbook'; subFamilyName = 'Italic'; fullName = 'Century Schoolbook Italic'; postscriptName = 'CenturySchoolbook-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'SCRIPTBL.TTF'; family = 'Script MT Bold'; subFamilyName = 'Regular'; fullName = 'Script MT Bold'; postscriptName = 'ScriptMTBold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'segmdl2.ttf'; family = 'Segoe MDL2 Assets'; subFamilyName = 'Regular'; fullName = 'Segoe MDL2 Assets'; postscriptName = 'SegoeMDL2Assets'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'segoepr.ttf'; family = 'Segoe Print'; subFamilyName = 'Regular'; fullName = 'Segoe Print'; postscriptName = 'SegoePrint'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'segoeprb.ttf'; family = 'Segoe Print'; subFamilyName = 'Bold'; fullName = 'Segoe Print Bold'; postscriptName = 'SegoePrint-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'segoesc.ttf'; family = 'Segoe Script'; subFamilyName = 'Regular'; fullName = 'Segoe Script'; postscriptName = 'SegoeScript'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'segoescb.ttf'; family = 'Segoe Script'; subFamilyName = 'Bold'; fullName = 'Segoe Script Bold'; postscriptName = 'SegoeScript-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'segoeui.ttf'; family = 'Segoe UI'; subFamilyName = 'Regular'; fullName = 'Segoe UI'; postscriptName = 'SegoeUI'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'segoeuib.ttf'; family = 'Segoe UI'; subFamilyName = 'Bold'; fullName = 'Segoe UI Bold'; postscriptName = 'SegoeUI-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'segoeuii.ttf'; family = 'Segoe UI'; subFamilyName = 'Italic'; fullName = 'Segoe UI Italic'; postscriptName = 'SegoeUI-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'segoeuil.ttf'; family = 'Segoe UI'; subFamilyName = 'Light'; fullName = 'Segoe UI Light'; postscriptName = 'SegoeUI-Light'; style = 'NORMAL'; stretch = 5; weight = 300; };
{fileName = 'segoeuisl.ttf'; family = 'Segoe UI'; subFamilyName = 'Semilight'; fullName = 'Segoe UI Semilight'; postscriptName = 'SegoeUI-Semilight'; style = 'NORMAL'; stretch = 5; weight = 350; };
{fileName = 'segoeuiz.ttf'; family = 'Segoe UI'; subFamilyName = 'Bold Italic'; fullName = 'Segoe UI Bold Italic'; postscriptName = 'SegoeUI-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'seguibl.ttf'; family = 'Segoe UI'; subFamilyName = 'Black'; fullName = 'Segoe UI Black'; postscriptName = 'SegoeUIBlack'; style = 'NORMAL'; stretch = 5; weight = 900; };
{fileName = 'seguibli.ttf'; family = 'Segoe UI'; subFamilyName = 'Black Italic'; fullName = 'Segoe UI Black Italic'; postscriptName = 'SegoeUIBlack-Italic'; style = 'ITALIC'; stretch = 5; weight = 900; };
{fileName = 'seguiemj.ttf'; family = 'Segoe UI Emoji'; subFamilyName = 'Regular'; fullName = 'Segoe UI Emoji'; postscriptName = 'SegoeUIEmoji'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'seguihis.ttf'; family = 'Segoe UI Historic'; subFamilyName = 'Regular'; fullName = 'Segoe UI Historic'; postscriptName = 'SegoeUIHistoric'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'seguili.ttf'; family = 'Segoe UI'; subFamilyName = 'Light Italic'; fullName = 'Segoe UI Light Italic'; postscriptName = 'SegoeUI-LightItalic'; style = 'ITALIC'; stretch = 5; weight = 300; };
{fileName = 'seguisb.ttf'; family = 'Segoe UI'; subFamilyName = 'Semibold'; fullName = 'Segoe UI Semibold'; postscriptName = 'SegoeUI-Semibold'; style = 'NORMAL'; stretch = 5; weight = 600; };
{fileName = 'seguisbi.ttf'; family = 'Segoe UI'; subFamilyName = 'Semibold Italic'; fullName = 'Segoe UI Semibold Italic'; postscriptName = 'SegoeUI-SemiboldItalic'; style = 'ITALIC'; stretch = 5; weight = 600; };
{fileName = 'seguisli.ttf'; family = 'Segoe UI'; subFamilyName = 'Semilight Italic'; fullName = 'Segoe UI Semilight Italic'; postscriptName = 'SegoeUI-SemilightItalic'; style = 'ITALIC'; stretch = 5; weight = 350; };
{fileName = 'seguisym.ttf'; family = 'Segoe UI Symbol'; subFamilyName = 'Regular'; fullName = 'Segoe UI Symbol'; postscriptName = 'SegoeUISymbol'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'SHOWG.TTF'; family = 'Showcard Gothic'; subFamilyName = 'Regular'; fullName = 'Showcard Gothic'; postscriptName = 'ShowcardGothic-Reg'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'simsunb.ttf'; family = 'SimSun-ExtB'; subFamilyName = 'Regular'; fullName = 'SimSun-ExtB'; postscriptName = 'SimSun-ExtB'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'SNAP____.TTF'; family = 'Snap ITC'; subFamilyName = 'Regular'; fullName = 'Snap ITC'; postscriptName = 'SnapITC-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'STENCIL.TTF'; family = 'Stencil'; subFamilyName = 'Regular'; fullName = 'Stencil'; postscriptName = 'Stencil'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'sylfaen.ttf'; family = 'Sylfaen'; subFamilyName = 'Regular'; fullName = 'Sylfaen'; postscriptName = 'Sylfaen'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'symbol.ttf'; family = 'Symbol'; subFamilyName = 'Regular'; fullName = 'Symbol'; postscriptName = 'SymbolMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'tahoma.ttf'; family = 'Tahoma'; subFamilyName = 'Regular'; fullName = 'Tahoma'; postscriptName = 'Tahoma'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'tahomabd.ttf'; family = 'Tahoma'; subFamilyName = 'Bold'; fullName = 'Tahoma Bold'; postscriptName = 'Tahoma-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'taile.ttf'; family = 'Microsoft Tai Le'; subFamilyName = 'Regular'; fullName = 'Microsoft Tai Le'; postscriptName = 'MicrosoftTaiLe'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'taileb.ttf'; family = 'Microsoft Tai Le'; subFamilyName = 'Bold'; fullName = 'Microsoft Tai Le Bold'; postscriptName = 'MicrosoftTaiLe-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'TCBI____.TTF'; family = 'Tw Cen MT'; subFamilyName = 'Bold Italic'; fullName = 'Tw Cen MT Bold Italic'; postscriptName = 'TwCenMT-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'TCB_____.TTF'; family = 'Tw Cen MT'; subFamilyName = 'Bold'; fullName = 'Tw Cen MT Bold'; postscriptName = 'TwCenMT-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'TCCB____.TTF'; family = 'Tw Cen MT Condensed'; subFamilyName = 'Bold'; fullName = 'Tw Cen MT Condensed Bold'; postscriptName = 'TwCenMT-CondensedBold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'TCCEB.TTF'; family = 'Tw Cen MT Condensed Extra Bold'; subFamilyName = 'Regular'; fullName = 'Tw Cen MT Condensed Extra Bold'; postscriptName = 'TwCenMT-CondensedExtraBold'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'TCCM____.TTF'; family = 'Tw Cen MT Condensed'; subFamilyName = 'Regular'; fullName = 'Tw Cen MT Condensed'; postscriptName = 'TwCenMT-Condensed'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'TCMI____.TTF'; family = 'Tw Cen MT'; subFamilyName = 'Italic'; fullName = 'Tw Cen MT Italic'; postscriptName = 'TwCenMT-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'TCM_____.TTF'; family = 'Tw Cen MT'; subFamilyName = 'Regular'; fullName = 'Tw Cen MT'; postscriptName = 'TwCenMT-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'TEMPSITC.TTF'; family = 'Tempus Sans ITC'; subFamilyName = 'Regular'; fullName = 'Tempus Sans ITC'; postscriptName = 'TempusSansITC'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'times.ttf'; family = 'Times New Roman'; subFamilyName = 'Regular'; fullName = 'Times New Roman'; postscriptName = 'TimesNewRomanPSMT'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'timesbd.ttf'; family = 'Times New Roman'; subFamilyName = 'Bold'; fullName = 'Times New Roman Bold'; postscriptName = 'TimesNewRomanPS-BoldMT'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'timesbi.ttf'; family = 'Times New Roman'; subFamilyName = 'Bold Italic'; fullName = 'Times New Roman Bold Italic'; postscriptName = 'TimesNewRomanPS-BoldItalicMT'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'timesi.ttf'; family = 'Times New Roman'; subFamilyName = 'Italic'; fullName = 'Times New Roman Italic'; postscriptName = 'TimesNewRomanPS-ItalicMT'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'trebuc.ttf'; family = 'Trebuchet MS'; subFamilyName = 'Regular'; fullName = 'Trebuchet MS'; postscriptName = 'TrebuchetMS'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'trebucbd.ttf'; family = 'Trebuchet MS'; subFamilyName = 'Bold'; fullName = 'Trebuchet MS Bold'; postscriptName = 'TrebuchetMS-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'trebucbi.ttf'; family = 'Trebuchet MS'; subFamilyName = 'Bold Italic'; fullName = 'Trebuchet MS Bold Italic'; postscriptName = 'Trebuchet-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'trebucit.ttf'; family = 'Trebuchet MS'; subFamilyName = 'Italic'; fullName = 'Trebuchet MS Italic'; postscriptName = 'TrebuchetMS-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'verdana.ttf'; family = 'Verdana'; subFamilyName = 'Regular'; fullName = 'Verdana'; postscriptName = 'Verdana'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'verdanab.ttf'; family = 'Verdana'; subFamilyName = 'Bold'; fullName = 'Verdana Bold'; postscriptName = 'Verdana-Bold'; style = 'NORMAL'; stretch = 5; weight = 700; };
{fileName = 'verdanai.ttf'; family = 'Verdana'; subFamilyName = 'Italic'; fullName = 'Verdana Italic'; postscriptName = 'Verdana-Italic'; style = 'ITALIC'; stretch = 5; weight = 400; };
{fileName = 'verdanaz.ttf'; family = 'Verdana'; subFamilyName = 'Bold Italic'; fullName = 'Verdana Bold Italic'; postscriptName = 'Verdana-BoldItalic'; style = 'ITALIC'; stretch = 5; weight = 700; };
{fileName = 'VINERITC.TTF'; family = 'Viner Hand ITC'; subFamilyName = 'Regular'; fullName = 'Viner Hand ITC'; postscriptName = 'VinerHandITC'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'VIVALDII.TTF'; family = 'Vivaldi'; subFamilyName = 'Italic'; fullName = 'Vivaldi Italic'; postscriptName = 'Vivaldii'; style = 'ITALIC'; stretch = 3; weight = 400; };
{fileName = 'VLADIMIR.TTF'; family = 'Vladimir Script'; subFamilyName = 'Regular'; fullName = 'Vladimir Script'; postscriptName = 'VladimirScript'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'webdings.ttf'; family = 'Webdings'; subFamilyName = 'Regular'; fullName = 'Webdings'; postscriptName = 'Webdings'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'wingding.ttf'; family = 'Wingdings'; subFamilyName = 'Regular'; fullName = 'Wingdings'; postscriptName = 'Wingdings-Regular'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'WINGDNG2.TTF'; family = 'Wingdings 2'; subFamilyName = 'Regular'; fullName = 'Wingdings 2'; postscriptName = 'Wingdings2'; style = 'NORMAL'; stretch = 5; weight = 400; };
{fileName = 'WINGDNG3.TTF'; family = 'Wingdings 3'; subFamilyName = 'Regular'; fullName = 'Wingdings 3'; postscriptName = 'Wingdings3'; style = 'NORMAL'; stretch = 5; weight = 400; };
};
